name: Manage Issues

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform on issues'
        required: true
        default: 'close'
        type: choice
        options:
        - close
        - delete_all
        - delete_closed

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Manage issues
        run: |
          case "${{ github.event.inputs.action }}" in
            "close")
              gh issue list --state open --limit 1000 --json number --jq '.[].number' | xargs -I {} gh issue close {}
              echo "All open issues have been closed."
              ;;
            "delete_all")
              gh issue list --state all --limit 1000 --json number --jq '.[].number' | xargs -I {} gh issue delete {} --yes
              echo "All issues have been deleted."
              ;;
            "delete_closed")
              gh issue list --state closed --limit 1000 --json number --jq '.[].number' | xargs -I {} gh issue delete {} --yes
              echo "All closed issues have been deleted."
              ;;
            *)
              echo "Invalid action specified."
              exit 1
              ;;
          esac
