name: Close All Open Issues

on:
  workflow_dispatch:  # This allows manual triggering only

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        uses: cli/cli@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close all open issues
        run: |
          gh issue list --state open --limit 1000 --json number --jq '.[].number' | xargs -I {} gh issue close {}